[project]
name = 'Social-Media-Authenticity-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.humble-brag-optimization-service]
path = 'contracts/humble-brag-optimization-service.clar'
clarity_version = 3
epoch = 'latest'

[contracts.spontaneous-moment-scheduler]
path = 'contracts/spontaneous-moment-scheduler.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
